import { normalizeDesignLayers, editableLayerStyles } from "./design-layers";

// No generated script can execute. Only this trusted, nonce-bound inspector
// runs in the opaque-origin iframe; it has no preload or host capabilities.
export function designFrameHtml(
  html: string,
  nonce: string,
  inspect = true,
): string {
  if (!/^[a-zA-Z0-9-]+$/.test(nonce)) throw new Error("Invalid frame nonce");
  const policy = `default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; img-src data:; font-src data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'`;
  const inspector = inspect
    ? `<script nonce="${nonce}">
      const send=(t,hover=false)=>{if(!(t instanceof Element))return;const r=t.getBoundingClientRect();const css=getComputedStyle(t);const computedStyles=Object.fromEntries(${JSON.stringify(editableLayerStyles)}.map(k=>[k,css.getPropertyValue(k)]));if(t.parentElement){const pc=getComputedStyle(t.parentElement);computedStyles['parent-layout']=pc.display.includes('grid')?'grid':pc.display.includes('flex')?(pc.flexDirection.startsWith('column')?'column':'row'):'block'}parent.postMessage({type:'bubble-design-select',nonce:${JSON.stringify(nonce)},hover,anchor:{computedStyles,nodeId:t.getAttribute('data-bubble-node-id')||undefined,text:(t.textContent||'').trim().slice(0,180),rect:{x:r.x,y:r.y,width:r.width,height:r.height}}},'*')};
      document.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();send(e.target)},true);
      document.addEventListener('submit',e=>e.preventDefault(),true);
      const nodes=()=>[...document.querySelectorAll('[data-bubble-node-id]')];
      const box=t=>{const r=t.getBoundingClientRect();return {x:r.x+scrollX,y:r.y+scrollY,width:r.width,height:r.height}};
      const reply=(type,request,body)=>parent.postMessage({type,nonce:${JSON.stringify(nonce)},request,...body},'*');
      const byId=id=>nodes().find(t=>t.getAttribute('data-bubble-node-id')===id);
      const flow=e=>{const c=getComputedStyle(e);if(c.display.includes('grid'))return 'grid';if(c.display.includes('flex'))return c.flexDirection.startsWith('column')?'column':'row';return 'stack'};
      let drag=null;
      const cbOf=(t,c)=>{let e=c.position==='fixed'?null:t.parentElement;while(e&&e!==document.documentElement&&getComputedStyle(e).position==='static')e=e.parentElement;if(!e||e===document.documentElement)return {x:0,y:0,width:document.documentElement.clientWidth,height:document.documentElement.clientHeight};const r=box(e),s=getComputedStyle(e),bl=parseFloat(s.borderLeftWidth)||0,bt=parseFloat(s.borderTopWidth)||0;return {x:r.x+bl,y:r.y+bt,width:e.clientWidth,height:e.clientHeight}};
      const layout=t=>{const c=getComputedStyle(t);const flowKid=k=>k.hasAttribute('data-bubble-node-id')&&k.getClientRects().length&&!['absolute','fixed'].includes(getComputedStyle(k).position);const holder=(c.position==='absolute'||c.position==='fixed')?(t.offsetParent||document.body):t.parentElement;return {rect:box(t),display:c.display,direction:flow(t),rowGap:parseFloat(c.rowGap)||0,columnGap:parseFloat(c.columnGap)||0,padding:[c.paddingTop,c.paddingRight,c.paddingBottom,c.paddingLeft].map(v=>parseFloat(v)||0),position:c.position,cb:cbOf(t,c),children:[...t.children].filter(flowKid).slice(0,200).map(k=>({id:k.getAttribute('data-bubble-node-id'),rect:box(k)})),siblings:holder?[...holder.children].filter(k=>k!==t&&k.hasAttribute('data-bubble-node-id')&&k.getClientRects().length).slice(0,100).map(box):[]}};
      const INH=new Set(['color','font','font-family','font-size','font-style','font-weight','font-variant','font-kerning','font-feature-settings','line-height','letter-spacing','word-spacing','text-align','text-indent','text-transform','text-shadow','white-space','word-break','overflow-wrap','direction','visibility','cursor','list-style','list-style-type','-webkit-font-smoothing']);
      const decls=t=>{const out=[];let q='',depth=0,s='';const flush=()=>{const m=/^\\s*(-?[a-zA-Z][-a-zA-Z0-9]*)\\s*:\\s*([\\s\\S]+?)\\s*$/.exec(s);if(m&&!m[1].startsWith('--'))out.push([m[1].toLowerCase(),m[2]]);s=''};for(const ch of t){if(q){s+=ch;if(ch===q)q='';continue}if(ch==='"'||ch==="'"){q=ch;s+=ch;continue}if(ch==='(')depth++;if(ch===')')depth--;if(ch===';'&&depth<=0){flush();continue}s+=ch}flush();return out};
      const parts=s=>{const r=[];let d=0,cur='';for(const ch of s){if(ch==='('||ch==='[')d++;if(ch===')'||ch===']')d--;if(ch===','&&!d){r.push(cur);cur=''}else cur+=ch}r.push(cur);return r.map(x=>x.trim()).filter(Boolean)};
      const spec=s=>{s=s.replace(/::[\\w-]+/g,'').replace(/:where\\([^)]*\\)/g,'');const a=(s.match(/#[\\w-]+/g)||[]).length,b=(s.match(/\\.[\\w-]+|\\[[^\\]]*\\]|:[\\w-]+/g)||[]).length,c=(s.replace(/\\[[^\\]]*\\]|\\([^)]*\\)|[.#:][\\w-]+/g,'').match(/[a-zA-Z][\\w-]*/g)||[]).length;return a*1e6+b*1e3+c};
      let ruleList=null;
      const rules=()=>{if(ruleList)return ruleList;const out=[];const walk=l=>{for(const r of l){if(r instanceof CSSStyleRule)out.push(r);else if(r instanceof CSSMediaRule){if(matchMedia(r.media.mediaText).matches)walk(r.cssRules)}else if(r instanceof CSSSupportsRule){if(CSS.supports(r.conditionText))walk(r.cssRules)}else if(typeof CSSLayerBlockRule!=='undefined'&&r instanceof CSSLayerBlockRule)walk(r.cssRules)}};for(const s of document.styleSheets){if(s.ownerNode?.hasAttribute?.('data-bubble-frame'))continue;try{walk(s.cssRules)}catch{}}return ruleList=out};
      const authored=t=>{const hits=[];rules().forEach((r,i)=>{let best=-1;for(const p of parts(r.selectorText)){try{if(t.matches(p))best=Math.max(best,spec(p))}catch{}}if(best>=0)hits.push([best,i,r])});hits.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const m=new Map();const put=(k,v)=>{const imp=/!\\s*important$/i.test(v);if(m.get(k)?.imp&&!imp)return;m.set(k,{v,imp})};for(const h of hits)for(const [k,v] of decls(h[2].style.cssText))put(k,v);const saved=t.getAttribute('data-bubble-orig-style');const inline=saved===null?t.getAttribute('style'):saved==='bubble:none'?'':saved;for(const [k,v] of decls(inline||''))if(!(k==='visibility'&&t.hasAttribute('data-bubble-masked')))put(k,v);return [...m].map(([k,o])=>[k,o.v])};
      const labelOf=e=>e===document.body?'body':e===document.documentElement?'html':e.classList[0]?'.'+e.classList[0]:(e.getAttribute('data-bubble-layer-name')||e.tagName.toLowerCase());
      const cssOf=t=>{const own=authored(t);const seen=new Set(own.map(d=>d[0]));const inherited=[];for(let e=t.parentElement;e&&inherited.length<8;e=e.parentElement){const ds=authored(e).filter(([k])=>INH.has(k)&&!seen.has(k));ds.forEach(([k])=>seen.add(k));if(ds.length)inherited.push({id:e.getAttribute('data-bubble-node-id')||undefined,label:labelOf(e),decls:ds.slice(0,40)})}return {tag:t.tagName.toLowerCase(),text:(t.textContent||'').replace(/\\s+/g,' ').trim().slice(0,80),own:own.slice(0,80),inherited}};
      const layerKids=c=>[...c.children].filter(k=>k.hasAttribute('data-bubble-node-id')&&!k.hasAttribute('data-bubble-insert-preview'));
      const shown=k=>k.getClientRects().length&&!['absolute','fixed'].includes(getComputedStyle(k).position);
      const layerOf=e=>{while(e&&e!==document.body&&!e.hasAttribute('data-bubble-node-id'))e=e.parentElement;return e||document.body};
      const leaf=e=>['img','svg','input','textarea','select','button','video','canvas','hr','a'].includes(e.tagName.toLowerCase())||[...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())||(!layerKids(e).length&&!!(e.textContent||'').trim());
      const nameOf=e=>e===document.body?null:(e.getAttribute('data-bubble-layer-name')||(e.classList[0]?'.'+e.classList[0]:e.tagName.toLowerCase()));
      const NOKIDS=new Set(['p','h1','h2','h3','h4','h5','h6','a','button','label','select','option','pre','table','thead','tbody','tfoot','tr','svg']);const TABLE=new Set(['table','thead','tbody','tfoot','tr']);const dropAt=(x,y)=>{let t=document.elementFromPoint(x,y);if(!t||t===document.documentElement)t=document.body;const sv=t.closest&&t.closest('svg');if(sv)t=sv;const e=layerOf(t);let c=e,ref=null;if(e!==document.body&&leaf(e)){ref=e;c=layerOf(e.parentElement)}while(c!==document.body&&NOKIDS.has(c.tagName.toLowerCase())){const tb=TABLE.has(c.tagName.toLowerCase())?c.closest('table'):null;ref=tb?layerOf(tb):c;c=layerOf(ref.parentElement)}if(c!==document.body&&c.closest('[data-bubble-locked="true"]'))return null;
        const all=layerKids(c),vis=all.filter(shown),dir=flow(c),axis=dir==='row'||dir==='grid'?'x':'y';let index;
        const after=(r)=>dir==='grid'?(y>r.bottom||(y>=r.top&&x>r.left+r.width/2)):axis==='x'?x>r.left+r.width/2:y>r.top+r.height/2;
        if(ref&&vis.includes(ref))index=vis.indexOf(ref)+(after(ref.getBoundingClientRect())?1:0);else if(vis.length){let best=0,bd=Infinity;vis.forEach((k,i)=>{const r=k.getBoundingClientRect();const d=Math.hypot(Math.max(r.left-x,0,x-r.right),Math.max(r.top-y,0,y-r.bottom));if(d<bd){bd=d;best=i}});index=best+(after(vis[best].getBoundingClientRect())?1:0)}else index=0;
        const cb=box(c),cs=getComputedStyle(c),pl=parseFloat(cs.paddingLeft)||0,pr=parseFloat(cs.paddingRight)||0,pt=parseFloat(cs.paddingTop)||0;let line;
        const prev=vis[index-1]&&box(vis[index-1]),next=vis[index]&&box(vis[index]);
        if(!prev&&!next)line={x:cb.x+pl,y:cb.y+pt,width:Math.max(cb.width-pl-pr,8),height:0};
        else if(axis==='x'){const a=prev?prev.x+prev.width:next.x-4,b=next?next.x:prev.x+prev.width+4,ref2=next||prev;line={x:(a+b)/2,y:ref2.y,width:0,height:ref2.height}}
        else{const a=prev?prev.y+prev.height:next.y-4,b=next?next.y:prev.y+prev.height+4;line={x:cb.x+pl,y:(a+b)/2,width:Math.max(cb.width-pl-pr,8),height:0}}
        const domIndex=index<vis.length?all.indexOf(vis[index]):vis.length?all.indexOf(vis[vis.length-1])+1:all.length;const near=ref||vis[index-1]||vis[index];
        return {containerId:c===document.body?null:c.getAttribute('data-bubble-node-id'),index:domIndex,position:index+1,count:vis.length+1,direction:dir,name:nameOf(c),line,containerTag:c.tagName.toLowerCase(),nearTag:near?near.tagName.toLowerCase():null}};
      window.addEventListener('message',e=>{const d=e.data;if(e.source!==parent||d?.nonce!==${JSON.stringify(nonce)})return;
        if(d.type==='bubble-design-drag-start'){const t=byId(d.nodeId);if(!t||t.closest('[data-bubble-locked="true"]')||!t.parentElement||getComputedStyle(t).position==='absolute'||getComputedStyle(t).position==='fixed'){reply('bubble-design-drag-state',d.request,{ok:false});return}drag={node:t,parent:t.parentElement,next:t.nextSibling,style:t.getAttribute('style'),at:null,origin:[...t.parentElement.children].filter(k=>k!==t&&k.hasAttribute('data-bubble-node-id')).indexOf(t.nextElementSibling)};if(drag.origin<0)drag.origin=[...t.parentElement.children].filter(k=>k!==t&&k.hasAttribute('data-bubble-node-id')).length;t.style.setProperty('pointer-events','none','important');t.style.setProperty('opacity','.35','important');t.style.setProperty('outline','2px dashed rgba(13,153,255,.7)','important');t.style.setProperty('outline-offset','-2px','important');reply('bubble-design-drag-state',d.request,{ok:true});return}
        if(d.type==='bubble-design-drag-over'&&drag&&Number.isFinite(d.x)&&Number.isFinite(d.y)){const n=drag.node;let c=null;for(let e=document.elementFromPoint(d.x,d.y);e&&e!==document.documentElement;e=e.parentElement){if(e===n||n.contains(e)||!e.hasAttribute('data-bubble-node-id'))continue;if(e.closest('[data-bubble-locked="true"]'))continue;if(e===drag.parent){c=e;break}if(!/flex|grid/.test(getComputedStyle(e).display))continue;if(e.parentElement===drag.parent){const r=e.getBoundingClientRect(),m=Math.min(r.width,r.height)*.25;if(d.x<r.left+m||d.x>r.right-m||d.y<r.top+m||d.y>r.bottom-m)continue}c=e;break}
          if(!c)c=drag.parent;const kids=[...c.children].filter(k=>k!==n&&k.hasAttribute('data-bubble-node-id'));const vis=kids.filter(k=>getComputedStyle(k).display!=='none');const dir=flow(c);let index=0;if(vis.length){let best=0,bd=Infinity;vis.forEach((k,i)=>{const r=k.getBoundingClientRect();const dx=Math.max(r.left-d.x,0,d.x-r.right),dy=Math.max(r.top-d.y,0,d.y-r.bottom);const dist=Math.hypot(dx,dy);if(dist<bd){bd=dist;best=i}});const r=vis[best].getBoundingClientRect();const before=dir==='row'?d.x<r.left+r.width/2:dir==='column'||dir==='stack'?d.y<r.top+r.height/2:(d.y<r.top?true:d.y>r.bottom?false:d.x<r.left+r.width/2);index=kids.indexOf(vis[best])+(before?0:1)}
          const id=c.getAttribute('data-bubble-node-id');if(!drag.at||drag.at.id!==id||drag.at.index!==index){drag.at={id,index};const ref=kids[index];if(ref)c.insertBefore(n,ref);else if(kids.length)kids[kids.length-1].after(n);else c.appendChild(n)}
          reply('bubble-design-drag-state',d.request,{ok:true,containerId:id,index,position:vis.filter(k=>kids.indexOf(k)<index).length,count:vis.length+1,direction:dir,name:c.getAttribute('data-bubble-layer-name')||c.tagName.toLowerCase(),containerRect:box(c),rect:box(n),moved:c!==drag.parent||index!==drag.origin});return}
        if(d.type==='bubble-design-drag-end'&&drag){const n=drag.node;if(!d.commit){if(drag.next&&drag.next.parentNode===drag.parent)drag.parent.insertBefore(n,drag.next);else drag.parent.appendChild(n)}if(drag.style===null)n.removeAttribute('style');else n.setAttribute('style',drag.style);drag=null;reply('bubble-design-drag-state',d.request,{ok:true});return}
        if(d.type==='bubble-design-preview-size'){const t=byId(d.nodeId);if(!t){reply('bubble-design-rects',d.request,{rects:{},height:0});return}if(!t.hasAttribute('data-bubble-orig-style'))t.setAttribute('data-bubble-orig-style',t.getAttribute('style')??'bubble:none');for(const k of ['width','height'])if(typeof d[k]==='string'){if(d[k])t.style.setProperty(k,d[k],'important');else t.style.removeProperty(k)}reply('bubble-design-rects',d.request,{rects:{[d.nodeId]:box(t)},height:Math.ceil(document.body.scrollHeight)});return}
        if(d.type==='bubble-design-preview-reset'){document.querySelectorAll('[data-bubble-insert-preview]').forEach(n=>n.remove());document.querySelectorAll('[data-bubble-orig-style]').forEach(t=>{const v=t.getAttribute('data-bubble-orig-style');t.removeAttribute('data-bubble-orig-style');if(v==='bubble:none')t.removeAttribute('style');else t.setAttribute('style',v)});return}
        if(d.type==='bubble-design-nodes-in'&&d.rect&&[d.rect.x,d.rect.y,d.rect.width,d.rect.height].every(Number.isFinite)){const q=d.rect,inside=t=>{if(!t.getClientRects().length||getComputedStyle(t).visibility==='hidden')return false;const b=box(t);return b.width>0&&b.height>0&&b.x>=q.x-1&&b.y>=q.y-1&&b.x+b.width<=q.x+q.width+1&&b.y+b.height<=q.y+q.height+1};const hits=nodes().filter(inside);const top=hits.filter(t=>!hits.some(o=>o!==t&&o.contains(t))).slice(0,50);reply('bubble-design-rects',d.request,{height:0,rects:Object.fromEntries(top.map(t=>[t.getAttribute('data-bubble-node-id'),box(t)]))});return}
        if(d.type==='bubble-design-drop-target'&&Number.isFinite(d.x)&&Number.isFinite(d.y)){reply('bubble-design-insert',d.request,{target:dropAt(d.x,d.y)});return}
        if(d.type==='bubble-design-preview-insert'){document.querySelectorAll('[data-bubble-insert-preview]').forEach(n=>n.remove());const c=typeof d.containerId==='string'?byId(d.containerId):document.body;if(!c||typeof d.tag!=='string'||!/^[a-z][a-z0-9]*$/.test(d.tag)){reply('bubble-design-insert',d.request,{});return}const n=document.createElement(d.tag);n.setAttribute('data-bubble-insert-preview','');n.setAttribute('data-bubble-node-id','bubble-insert-preview');n.textContent=String(d.text||'').slice(0,200);const all=layerKids(c),at=all[d.index];if(at)c.insertBefore(n,at);else if(all.length)all[all.length-1].after(n);else c.appendChild(n);const css=getComputedStyle(n);reply('bubble-design-insert',d.request,{rect:box(n),styles:Object.fromEntries(['font-family','font-size','font-weight','line-height','letter-spacing','text-align','color','padding'].map(k=>[k,css.getPropertyValue(k)]))});return}
        if(d.type==='bubble-design-styles'){const t=typeof d.nodeId==='string'?byId(d.nodeId):document.body;reply('bubble-design-styles',d.request,{css:t?cssOf(t):null});return}
        if(d.type==='bubble-design-layout'){const t=byId(d.nodeId);reply('bubble-design-layout',d.request,{layout:t?layout(t):null});return}
        if(d.type==='bubble-design-preview-style'&&d.styles&&typeof d.styles==='object'){const t=byId(d.nodeId);if(!t){reply('bubble-design-layout',d.request,{layout:null});return}if(!t.hasAttribute('data-bubble-orig-style'))t.setAttribute('data-bubble-orig-style',t.getAttribute('style')??'bubble:none');for(const [k,v] of Object.entries(d.styles).slice(0,12)){if(typeof v!=='string'||!/^[a-z-]+$/.test(k))continue;if(v)t.style.setProperty(k,v,'important');else t.style.removeProperty(k)}reply('bubble-design-layout',d.request,{layout:layout(t)});return}
        if(d.type==='bubble-design-mask'){document.querySelectorAll('[data-bubble-masked]').forEach(t=>{t.style.visibility=t.getAttribute('data-bubble-masked');t.removeAttribute('data-bubble-masked')});const t=typeof d.nodeId==='string'&&nodes().find(t=>t.getAttribute('data-bubble-node-id')===d.nodeId);if(t){t.setAttribute('data-bubble-masked',t.style.visibility);t.style.visibility='hidden'}return}
        if(d.type==='bubble-design-measure'&&Array.isArray(d.ids)){const all=nodes();reply('bubble-design-rects',d.request,{height:Math.ceil(document.body.scrollHeight),rects:Object.fromEntries(d.ids.slice(0,500).map(id=>{const t=all.find(t=>t.getAttribute('data-bubble-node-id')===id);return [id,t&&t.getClientRects().length?box(t):null]}))});return}
        if(d.type==='bubble-design-snapshot'){const keys=${JSON.stringify(editableLayerStyles)};reply('bubble-design-snapshot',d.request,{nodes:nodes().slice(0,2000).map(t=>{const css=getComputedStyle(t);const p=t.parentElement?.closest('[data-bubble-node-id]');return {id:t.getAttribute('data-bubble-node-id'),parent:p?.getAttribute('data-bubble-node-id')||undefined,name:t.getAttribute('data-bubble-layer-name')||undefined,rect:box(t),text:[...t.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim().slice(0,200),styles:Object.fromEntries(keys.map(k=>[k,css.getPropertyValue(k)]))}})});return}
        if(d.type==='bubble-design-select-node'&&typeof d.nodeId==='string'){send([...document.querySelectorAll('[data-bubble-node-id]')].find(t=>t.getAttribute('data-bubble-node-id')===d.nodeId));return}if(d.type!=='bubble-design-hit-test'||!Number.isFinite(d.x)||!Number.isFinite(d.y))return;let t=document.elementFromPoint(d.x,d.y);if(t?.closest('[data-bubble-locked="true"]'))return;send(t,d.hover===true)});
      </script>`
    : "";
  // parse5 serializes a single document; insert CSP before all user styles.
  return normalizeDesignLayers(html).replace(
    "<head>",
    `<head><meta http-equiv="Content-Security-Policy" content="${policy}"><meta name="referrer" content="no-referrer"><style data-bubble-frame>html{color-scheme:light}body{margin:0}*{box-sizing:border-box}[data-bubble-hidden="true"]{display:none!important}</style>${inspector}`,
  );
}
