import type { ToolResultMetadata } from "../types.js";

export interface DisplayMessage {
  /** Stable identity, used as the transcript list key. Generated by the UI layer. */
  key?: string;
  role: "user" | "assistant" | "error";
  content: string;
  reasoning?: string;
  toolCalls?: DisplayToolCall[];
  parts?: DisplayMessagePart[];
  syntheticKind?: "ui_summary";
  hiddenCount?: number;
}

export type DisplayMessagePart = DisplayTextPart | DisplayToolsPart;

export interface DisplayTextPart {
  type: "text";
  content: string;
}

export interface DisplayToolsPart {
  type: "tools";
  toolCalls: DisplayToolCall[];
}

export interface DisplayToolCall {
  id: string;
  name: string;
  args: Record<string, any>;
  result?: string;
  isError?: boolean;
  metadata?: ToolResultMetadata;
  /** Set when the tool_start event was received. Used to render elapsed time. */
  startedAt?: number;
}

let __displayMessageCounter = 0;
export function nextDisplayMessageKey(prefix = "msg"): string {
  __displayMessageCounter += 1;
  return `${prefix}-${__displayMessageCounter}`;
}

export function appendTextPart(parts: DisplayMessagePart[], content: string): void {
  if (!content) return;
  const last = parts[parts.length - 1];
  if (last?.type === "text") {
    last.content += content;
  } else {
    parts.push({ type: "text", content });
  }
}

export function appendToolPart(parts: DisplayMessagePart[], toolCall: DisplayToolCall): void {
  const last = parts[parts.length - 1];
  if (last?.type === "tools") {
    last.toolCalls.push(toolCall);
  } else {
    parts.push({ type: "tools", toolCalls: [toolCall] });
  }
}

export function snapshotDisplayParts(parts: DisplayMessagePart[]): DisplayMessagePart[] {
  return parts.map((part) => {
    if (part.type === "text") {
      return { ...part };
    }
    return {
      type: "tools",
      toolCalls: part.toolCalls.map(cloneToolCall),
    };
  });
}

export function contentFromParts(parts: DisplayMessagePart[]): string {
  return parts
    .filter((part): part is DisplayTextPart => part.type === "text")
    .map((part) => part.content)
    .join("");
}

export function toolCallsFromParts(parts: DisplayMessagePart[]): DisplayToolCall[] {
  return parts.flatMap((part) => part.type === "tools" ? part.toolCalls : []);
}

const FULL_DETAIL_WINDOW = 24;
const MAX_OLD_CONTENT_CHARS = 1200;
const MAX_OLD_REASONING_CHARS = 600;
const MAX_OLD_TOOL_RESULT_CHARS = 800;

export function compactDisplayMessages(messages: DisplayMessage[]): DisplayMessage[] {
  if (messages.length === 0) {
    return messages;
  }

  const visible = messages.filter((message) => message.syntheticKind !== "ui_summary");
  const detailStart = Math.max(0, visible.length - FULL_DETAIL_WINDOW);
  return visible.map((message, index) => (
    index < detailStart ? compactDisplayMessage(message) : message
  ));
}

function compactDisplayMessage(message: DisplayMessage): DisplayMessage {
  if (message.syntheticKind === "ui_summary") {
    return message;
  }

  return {
    ...message,
    content: truncateText(message.content, MAX_OLD_CONTENT_CHARS),
    reasoning: message.reasoning
      ? truncateText(message.reasoning, MAX_OLD_REASONING_CHARS)
      : message.reasoning,
    toolCalls: message.toolCalls?.map(compactToolCall),
    parts: message.parts?.map(compactDisplayPart),
  };
}

function truncateText(value: string, maxChars: number): string {
  if (value.length <= maxChars) {
    return value;
  }

  const head = Math.max(1, Math.floor(maxChars * 0.7));
  const tail = Math.max(1, maxChars - head - 32);
  const omitted = value.length - head - tail;
  return `${value.slice(0, head)}\n...[${omitted} chars omitted for UI]...\n${value.slice(-tail)}`;
}

function cloneToolCall(toolCall: DisplayToolCall): DisplayToolCall {
  return {
    ...toolCall,
    args: { ...toolCall.args },
  };
}

function compactDisplayPart(part: DisplayMessagePart): DisplayMessagePart {
  if (part.type === "text") {
    return {
      ...part,
      content: truncateText(part.content, MAX_OLD_CONTENT_CHARS),
    };
  }
  return {
    type: "tools",
    toolCalls: part.toolCalls.map(compactToolCall),
  };
}

function compactToolCall(toolCall: DisplayToolCall): DisplayToolCall {
  return {
    ...toolCall,
    result: toolCall.result
      ? truncateText(toolCall.result, MAX_OLD_TOOL_RESULT_CHARS)
      : toolCall.result,
  };
}
