import type { Message, ToolResultMetadata } from "../types.js";

export type UserInputStatus = "queued" | "pending_steer";

export interface DisplayMessage {
  /** Stable identity, used as the transcript list key. Generated by the UI layer. */
  key?: string;
  role: "user" | "assistant" | "error";
  content: string;
  /** Correlates queued/steer placeholder rows with their lifecycle events. */
  clientId?: string;
  /** Badge for user input waiting to enter the run (QUEUED / STEER). */
  inputStatus?: UserInputStatus;
  reasoning?: string;
  toolCalls?: DisplayToolCall[];
  parts?: DisplayMessagePart[];
  syntheticKind?: "ui_summary" | "ui_compact_summary" | "ui_interrupt" | "ui_notice";
  /** Markdown body shown inside a `ui_compact_summary` card. */
  compactionSummary?: string;
  hiddenCount?: number;
  taskElapsedMs?: number;
  /** Backend configuration fingerprint reported for this model response. */
  systemFingerprint?: string;
}

export function userInputStatusBadgeLabel(status?: UserInputStatus): string | undefined {
  switch (status) {
    case "queued":
      return "QUEUED";
    case "pending_steer":
      return "STEER";
    default:
      return undefined;
  }
}

export function setUserInputStatus(message: DisplayMessage, inputStatus?: UserInputStatus): DisplayMessage {
  if (inputStatus) return { ...message, inputStatus };
  const { inputStatus: _inputStatus, ...rest } = message;
  return rest;
}

export function moveStatusMessageToEnd(
  messages: DisplayMessage[],
  key: string,
  inputStatus?: UserInputStatus,
): DisplayMessage[] {
  const index = messages.findIndex((message) => message.key === key);
  if (index === -1) return messages;
  const message = messages[index]!;
  return [
    ...messages.slice(0, index),
    ...messages.slice(index + 1),
    setUserInputStatus(message, inputStatus),
  ];
}

/**
 * Aborted assistant messages carry a model-facing interruption note appended
 * to their content (whole content, or a "\n\n"-joined suffix after partial
 * streamed text). That note is for the next model call, not the user — strip
 * it so only what the assistant actually said renders, and let the caller
 * show a dedicated interrupt indicator instead.
 */
export function stripInterruptedAssistantMarker(content: string, marker: string): string {
  if (!content || !marker) return content;
  if (content === marker) return "";
  const suffix = `\n\n${marker}`;
  if (content.endsWith(suffix)) return content.slice(0, -suffix.length);
  return content;
}

export type DisplayMessagePart = DisplayTextPart | DisplayToolsPart;

export interface DisplayTextPart {
  type: "text";
  content: string;
}

export interface DisplayToolsPart {
  type: "tools";
  toolCalls: DisplayToolCall[];
}

export interface DisplayToolCall {
  id: string;
  name: string;
  args: Record<string, any>;
  /**
   * Unparsed JSON string for tool arguments, populated during partial-streaming
   * before `args` resolves. Used as a fallback by trace-groups when extracting
   * a command preview.
   */
  rawArguments?: string;
  result?: string;
  isError?: boolean;
  metadata?: ToolResultMetadata;
  /** Set when the tool_start event was received. Used to render elapsed time. */
  startedAt?: number;
}

let __displayMessageCounter = 0;
export function nextDisplayMessageKey(prefix = "msg"): string {
  __displayMessageCounter += 1;
  return `${prefix}-${__displayMessageCounter}`;
}

export function appendTextPart(parts: DisplayMessagePart[], content: string): void {
  if (!content) return;
  const last = parts[parts.length - 1];
  if (last?.type === "text") {
    last.content += content;
  } else {
    parts.push({ type: "text", content });
  }
}

export function appendToolPart(parts: DisplayMessagePart[], toolCall: DisplayToolCall): void {
  const last = parts[parts.length - 1];
  if (last?.type === "tools") {
    last.toolCalls.push(toolCall);
  } else {
    parts.push({ type: "tools", toolCalls: [toolCall] });
  }
}

export function snapshotDisplayParts(parts: DisplayMessagePart[]): DisplayMessagePart[] {
  return parts.map((part) => {
    if (part.type === "text") {
      return { ...part };
    }
    return {
      type: "tools",
      toolCalls: part.toolCalls.map(cloneToolCall),
    };
  });
}

export function contentFromParts(parts: DisplayMessagePart[]): string {
  return parts
    .filter((part): part is DisplayTextPart => part.type === "text")
    .map((part) => part.content)
    .join("");
}

export function toolCallsFromParts(parts: DisplayMessagePart[]): DisplayToolCall[] {
  return parts.flatMap((part) => part.type === "tools" ? part.toolCalls : []);
}

function cloneToolCall(toolCall: DisplayToolCall): DisplayToolCall {
  return {
    ...toolCall,
    args: { ...toolCall.args },
  };
}

const PREVIOUS_SUMMARY_PREFIX = /^Previous conversation summary:\s*\n?([\s\S]*)$/;
const TURN_SUMMARY_PREFIX = /^Earlier in this turn \(compacted to free context\):\s*\n?([\s\S]*)$/;

/**
 * Find the most recent compaction summary embedded in the agent's system
 * messages. Bubble's compaction step rewrites the system transcript so that
 * the long-form summary lives in either a "Previous conversation summary:"
 * block or an "Earlier in this turn" block; we walk from newest to oldest and
 * return the first match so the UI can show the freshest summary.
 */
export function latestCompactionSummary(agentMessages: Message[]): string | undefined {
  for (let index = agentMessages.length - 1; index >= 0; index--) {
    const message = agentMessages[index];
    if (!message || typeof message.content !== "string") continue;
    // Summaries are meta messages since 0.0.43; raw system form is legacy.
    const isSummaryCarrier = message.role === "system"
      || (message.role === "meta"
        && (message.kind === "compaction-summary" || message.kind === "subturn-compaction-summary"));
    if (!isSummaryCarrier) continue;
    const previousMatch = message.content.match(PREVIOUS_SUMMARY_PREFIX);
    if (previousMatch?.[1]?.trim()) return previousMatch[1].trim();
    const turnMatch = message.content.match(TURN_SUMMARY_PREFIX);
    if (turnMatch?.[1]?.trim()) return turnMatch[1].trim();
  }
  return undefined;
}
